const List<String> kEveryMomentTextLibrary = [
  "Every moment is a fresh start. I'm right here with you, taking every change one step at a time.",
  'You did great today. Take a well-deserved rest.',
  'Take a moment to thank your body.',
  'Remember to take good care of yourself.',
  'Your body loves you deeply.',
  'Move a little, and let your body know how much you value it.',
  'Your worries are seen, and every ounce of your effort is safely recorded right here.',
  'Time and I are here, witnessing every little step of your progress.',
  "Thank you for never giving up on yourself. You've been through a lot.",
  'Feeling scared but facing it bravely anyway——you are doing absolutely amazing.',
  'Please know that no matter how hard it is right now, you are stepping closer, bit by bit, to the person you want to be.',
  'Give it time. Every single attempt holds its own beautiful meaning.',
  'Every single cell in your body is working around the clock, loving you with all its might.',
  "Congratulations on having a deep conversation with yourself. Remember, whenever you need me, I'll be right here waiting.",
  'Take it slow. We have a whole lifetime to learn how to love ourselves.',
  'No matter how today went, let me softly remind you: "You are truly amazing."',
  'You treated yourself with so much care today.',
  'Please remember to take care of yourself. Putting how you feel first is the most important thing of all.',
  '"To love oneself is the beginning of a lifelong romance."',
  'The universe loves you. Every act of self-care invites the universe to support and cherish you in return.',
  'When you truly love yourself, the whole universe comes together to support and care for you.',
  'Your mind believes what you repeat to it. With every attempt and every repetition, life gently rewards you with better gifts.',
  'All will be fine, just keep going.',
];