const List<String> kWarmSentencesTimer = [
  'Gently return your attention to your body.\n\nYour body is waiting to be heard.',
  'Let the rest of the world fade away.\n\nThis moment only belongs to you.',
  'For this moment, simply take care of yourself.',
  'Let the outside world grow quieter.',
  'Together, let\'s create a space where you can simply be.',
  'For now, this moment belongs only to you.',
  'Whenever your attention drifts away, softly come back to yourself.',
  'Look away from the screen and notice how your body feels.',
  'Take a slow, deep breath.\n\nAs you exhale, let the noise of the world remain outside.\n\nFor this moment, it\'s just you and your body.',
  'Listen closely.\n\nYour body has something to tell you.',
  'This moment is ours.\n\nI\'ll stay right here with you.',
  'Your struggles are seen.\n\nSo is every bit of effort you\'ve made along the way.',
  'You\'re not alone in this.\n\nMany others are walking a similar path.',
  'It\'s okay to feel uncertain.\n\nYou don\'t have to face it all at once.',
  'Everything you\'re feeling is real.\n\nThey\'re welcome here.',
  'Your feelings make sense.',
  'I\'m here.\n\nYou\'re not alone.',
  'It\'s okay. I\'ll stay with you.',
  'There\'s no rush.\n\nI\'m here whenever you need me.',
  'You don\'t have to hold everything together here.\n\nYou can simply be yourself.\n\nI\'ll stay with you through it.',
  'I see how hard you\'ve been trying.\n\nThat effort matters.\n\nAnd so do you.',
  'Feeling a little storm inside?\n\nThat\'s okay. Every body has its cloudy days.\n\nWe\'ll get through this weather together.',
  'You\'re not alone.\n\nMany others are learning to be kinder to themselves, too.',
  'I\'m here with you. Take your time.',
  'Anxiety often arrives as a protector.\n\nWhen it sees that you\'re okay, it knows how to let go.',
  'Your body has its own rhythm.\n\nIt\'s okay to move a little slower.',
  'You don\'t have to rush.\n\nThings can get better one moment at a time.',
  'Anxiety may simply be trying to care for you.\n\nYou might quietly say, "Thank you for trying to keep me safe."',
  'Anxiety isn\'t trying to hurt you.\n\nIt\'s simply working a little too hard to keep you safe.\n\nYou can let it know that you\'re okay.',
  'Perhaps anxiety has been with you for so long that you\'ve forgotten why it came.\n\nAt its core, it was trying to protect you.\n\nYou might simply say, "Thank you for caring."',
  'Your body doesn\'t measure success or failure.\n\nIf nothing happens today, that\'s okay.\n\nYour body may simply be saying, "Not yet."',
  'Thoughts are like clouds.\n\nThey come and go.\n\nYou don\'t need to follow them.\n\nYou are the vast sky beyond them.',
  'Your body\'s rhythm doesn\'t need to keep up with anyone else\'s.',
  'You are not your thoughts.\n\nNotice them.\n\nBut you don\'t have to follow them.',
  'This moment is enough.\n\nTake your time.',
  'Sometimes discomfort is simply your body\'s way of asking to be heard.\n\nYou\'ve paused to listen.\n\nThat\'s where healing begins.',
  'Place a warm hand on your belly.\n\nLet its warmth spread gently inward.\n\nSoftening what feels tight.',
  'Your body knows how to let go.\n\nEach wave of movement is part of that process.',
  'Trust your body\'s quiet wisdom.\n\nIt knows more than you think.',
  'Soften your jaw.\n\nRelax your shoulders.\n\nLet your belly soften with your next breath.',
  'Bring your attention to the area that feels uncomfortable.\n\nBreathe into it gently.\n\nWith every exhale, allow a little more tension to let go.',
  'Your body is doing its best.\n\nYou don\'t have to force anything.\n\nSimply allow.',
  'The world can wait.\n\nNothing else needs your attention right now.\n\nJust listen to the quiet wisdom of your body.',
  'Imagine a circle of gentle light around you.\n\nA space that belongs entirely to you.\n\nOnly what you welcome is allowed in.',
  'Let the sounds around you fade into the distance.\n\nCome back to yourself.',
  'Stay with this feeling for a moment.\n\nYou may discover that you\'re stronger than you think.',
  'The world around you may change.\n\nYour kindness toward yourself can remain.',
  'This is your space.\n\nNothing to prove.\n\nNothing to hide.\n\nSimply be.',
  'The sounds outside are like a distant breeze.\n\nThey pass by without disturbing your inner calm.',
  'Your needs matter.\n\nAnd so do you.\n\nBoth deserve care, attention, and respect.',
  'The past has already passed.\n\nThis moment is new.',
  'I\'m here with the person you are today.\n\nAnd that\'s who matters in this moment.',
  'Every small step counts.\n\nThe willingness to try is already a sign of growth.',
  'In this safe space, you can be your own source of kindness.',
  'This is a safe space.\n\nNothing to fix.\n\nNothing to prove.\n\nSimply be yourself.',
  'Breathe in for 4.\n\nHold for 7.\n\nExhale slowly for 8.\n\nWith each breath, allow your body to soften.',
  'Take a deep breath.\n\nAs you inhale, invite gentleness in.\n\nAs you exhale, let go.',
  'Allow your breath to move like the ocean—\n\ncoming and going, wave after wave.\n\nSteady. Gentle. Present.',
  'Notice the quiet rhythm of being alive.\n\nBreathing. Present. Here.',
  'Take a deep breath.\n\nEvery breath is a chance to soften.\n\nEvery breath is a chance to begin again.',
  'Inhale for 4 seconds,\n\nHold for 7,\n\nThen exhale slowly for 8.\n\nLet go of anything you no longer need to carry.',
  'Deep within you is an ancient rhythm.\n\nSteady. Natural. Timeless.',
  'You are experiencing one of life\'s most natural processes.\n\nWelcome it.\n\nTrust it.',
  'Your body\'s needs are not flaws to overcome.\n\nThey are part of being human.\n\nNatural. Necessary. Beautiful.',
  'Forests carry the scent of earth.\n\nThe ocean carries the scent of salt and waves.\n\nYour body carries its own signs of life.',
  'Self-acceptance is one of the deepest forms of freedom.',
  'You don\'t need to be perfect.\n\nYou only need to be real.',
  'Nothing in nature rushes.\n\nAnd yet everything arrives in its own season.',
  'Every sound your body makes is a reminder of life in motion.',
  'Here, you can set down every label.\n\nYou can simply be you.\n\nAlive. Real. Whole.',
  'Let yourself soften.\n\nLet yourself release.\n\nAnd simply experience the gift of being alive.',
  'Simply notice your body.\n\nNotice this moment.\n\nNothing needs to happen right now.',
  'Stay with yourself for a little longer.\n\nThis space is yours.',
  'Every attempt is a step forward.\n\nTake your time.\n\nTrust your body\'s rhythm.',
  'Each time you stay a little longer, you\'re gently expanding what feels safe.',
  'We\'re not trying to achieve anything.\n\nWe\'re simply allowing your body to move at its own pace.',
];
